# Generated by Django 5.0.4 on 2024-04-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_created_date_contact_date_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='date_sent',
            new_name='sent_at',
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
