# Generated by Django 5.0.4 on 2024-04-28 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_date_sent_contact_sent_at_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='description',
            new_name='message',
        ),
    ]
