# Generated by Django 5.0.4 on 2024-05-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_collection_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
